config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:create, :new]

  resource :session

  get 'auth/:provider/callback', to: 'googles#create'
  get 'auth/failure', to: redirect('/')


  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update, :index]
    resources :posts, only: [:create, :update, :destroy, :index]
    resources :comments, only: [:create, :update, :destroy]
    resources :whisky, only: [:show, :index]
    resources :toasts, only: [:create]
    resources :friendships, only: [:create]
    resources :friends, only: [:index]
    resources :suggestions, only: [:index, :create, :update, :destroy]
    get "search", to: "searches#index"
    get "places", to: "places#show"
    get "friend", to: "friend#index"
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  include PgSearch
  multisearchable against: [:user_name, :email]

  validates :user_name, :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_attached_file :picture, styles: { medium: "100x100>", profile_pic: "256x256<", thumb: "32x32>" }, default_url: "user_default_:style.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  has_attached_file :background_picture, styles: { medium: "880"}
  validates_attachment_content_type :background_picture, content_type: /\Aimage\/.*\Z/

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :posts
  has_many :whiskys, through: :posts, source: :whisky
  has_many :comments
  has_many :toasts,
    class_name: 'Toast',
    foreign_key: :user_id

  has_many :friendships,
    class_name: "Friendship"

  has_many :friends, through: :friendships, source: :friend

  has_many :suggestions,
    class_name: 'Suggestion',
    foreign_key: :user_id

  has_many :received_suggestions,
    class_name: 'Suggestion',
    foreign_key: :recipient_id

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.user_name = auth["info"]["name"]
      user.email = auth["info"]["email"]

      user.password_digest = BCrypt::Password.create('catdog')

    end
  end


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController

    def index
      @users = User.where("(user_name ~ ?) OR (user_name ~ ?) OR (user_name ~ ?)", params[:query], params[:upcase], params[:lowercase])


      render :index
    end


    def show
      @user = User.includes(:whiskys, received_suggestions: [:whisky, :user]).find(params[:id])

      users_id = @user.id
      @posts = Post.includes(:user, :toasts, :toasters, :whisky, comments: [:user])
        .where("user_id = (?)", users_id).order(created_at: :desc).page(1).per(5)

      render :show
    end

    def update
      @user = User.find(current_user.id)

      if @user.update(user_params)
        render json: @user
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity
      end
    end


    private

    def user_params
      params.require(:user).permit(:user_name, :email, :picture, :background_picture)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :user_name, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<section class="sign-up">

  <ul class="sign-up-elements">
    <h1 class="greeting">Sign up for DISTILLD</h1>

    <form action="<%= users_url %>" method="post" class="user-new-form group">
        <%= auth_form %>
      <fieldset class="user-form-fieldset">
        <div class="user-input">
          <label for="form-email"></label>
            <input id="form-email" name="user[user_name]" value="<%= @user.user_name %>" placeholder="User name">
        </div>
        <div class="user-input">
          <label for="form-email"></label>
            <input id="form-email" name="user[email]" value="<%= @user.email %>" placeholder="Email address">
        </div>
        <div class="user-input">
          <label for="form-password"></label>
            <input type ="password" id="form-password" name="user[password]" value="" placeholder="Password">
        </div>
        <div class="submit">
          <button>Sign Up</button>
        </div>
      </fieldset>
    </form>
    <p class="new-session">Already a user? <a href="/session/new">Sign In</a></p>
    <p>
      OR
    </p>
    <a href="/auth/google_oauth2" id="google-sign-in"><img src="https://developers.google.com/accounts/images/sign-in-with-google.png" alt="" /></a>
  </ul>
</section>