config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:create, :new]

  resource :session

  get 'auth/:provider/callback', to: 'googles#create'
  get 'auth/failure', to: redirect('/')


  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update, :index]
    resources :posts, only: [:create, :update, :destroy, :index]
    resources :comments, only: [:create, :update, :destroy]
    resources :whisky, only: [:show, :index]
    resources :toasts, only: [:create]
    resources :friendships, only: [:create]
    resources :friends, only: [:index]
    resources :suggestions, only: [:index, :create, :update, :destroy]
    get "search", to: "searches#index"
    get "places", to: "places#show"
    get "friend", to: "friend#index"
  end


end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join('<br>').html_safe if flash[:errors] %>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="header-nav group">
    <h1 class="header-logo"><a href="">DISTILLD</a></h1>
    <ul class="header-list group">
      <li class="input">
          <input type="text" class="header-input-form-location" name="location" placeholder="Search for drinking spots..."value=""></input>
      </li>
        <li>
          <div class="name-items">
            <a href="#/users/<%= current_user.id %>" class="user-name"><%= current_user.user_name %></a>
            <ul class="dropdown">
              <li><a href="/#/users/<%= current_user.id %>/whiskys">Whiskys</a></li>
              <li><a href="/#/users/<%= current_user.id %>/friends">Friends</a></li>
              <li><a href="#/users/<%= current_user.id %>/settings">Settings</a></li>
            </ul>
          </div>
        </li>
      <li>
        <form action="<%= session_url %>" method="post">
          <%= auth_form %>
            <input type="hidden" name="_method" value="delete">
          <button class="sign-out">Sign Out</button>
        </form>
      </li>
    </ul>
    <ul class="mobile-header-list group">
        <li>
          <div class="name-items">
            <a class="user-name"><%= current_user.user_name %></a>
            <ul class="dropdown hidden">
              <li><a href="/#/users/<%= current_user.id %>/whiskys">Whiskys</a></li>
              <li><a href="/#/users/<%= current_user.id %>/friends">Friends</a></li>
              <li><a href="#/users/<%= current_user.id %>/settings">Settings</a></li>
            </ul>
          </div>
        </li>
        <script type="text/javascript">
        function toggleNavShow (){
          $('.dropdown')[1].classList.toggle('dropdown-show')
          };
          $('.user-name')[1].addEventListener('click', toggleNavShow)
        </script>
    </ul>
  </nav>
</header>

<script charset="utf-8">
  var input = this.$('.header-input-form-location'),
      searchBox = new google.maps.places.Autocomplete(input[0]),
      that = this;
      google.maps.event.addListener(searchBox, 'place_changed', function () {
        var place = searchBox.getPlace();
        var place_id = place.place_id;
        Backbone.history.navigate('places/' + place_id, { trigger: true })
      });


</script>

app/views/layouts/_session.html.erb
<section class="sign-in">

  <ul class="sign-in-elements">
    <h1 class="greeting">Log in to DISTILLD</h1>

    <form action="<%= session_url %>" method="post" class="session-new-form group">
        <%= auth_form %>
      <fieldset class="session-form-fieldset">
        <div class="session-input">
          <label for="form-email">Email address</label>
            <input id="form-email" name="user[email]" value="">
        </div>
        <div class="session-input">
          <label for="form-password">Password</label>
            <input type ="password" id="form-password" name="user[password]" value="">
        </div>
        <div class="submit">
          <button>Log In</button>
        </div>
      </fieldset>
    </form>

    <p class="new-user">Not yet a user? <a href="/users/new">Sign Up</a></p>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DISTILLD</title>
    <% if Rails.env.production? %>
      <% api_key = "ENV['GOOGLE_KEY']" %>
    <% else %>
      <% api_key = '' %>
    <% end %>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&<%= ENV['GOOGLE_KEY'] %>">
    </script>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:700italic,600,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,900,700italic,900italic' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="map"></div>

    <article class="error-messages">
      <%= render "layouts/errors" %>
    </article>



    <% if logged_in? %>
      <%= render "layouts/header" %>
    <% end %>

  <%= yield %>


  </body>
</html>